config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  root "posts#index", as: "home"
  get "/notifications", to: "notifications#check"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'my_registrations'
  }

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :users, path: 'profile', except: [:create, :destroy, :edit, :new, :update] do
    member do
      post 'follow', to: 'follows#create'  # Create a follow relationship
      delete 'unfollow', to: 'follows#destroy'  # Remove a follow relationship
    end

    resources :posts, only: [:create, :new, :edit, :update, :destroy]

    get 'following/index'
    get 'followers/index'
  end

  resources :follows, only: [:update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  def index
    # Find all the comments associated with the post
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_comments_url(@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_comments_url(@post), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to post_comments_url(@post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <%= image_tag comment.user.gravatar_url(:size => 30) %>
  <%= link_to "#{comment.user.email}", user_path(comment.user) %>
  <p>
    <%= comment.body %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: [post, Comment.new], url: post_comments_path(post)) do |form| %>
  <% if comment.errors.any? %>
    <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.label :body %>
  <%= form.text_area :body %>

  <%= form.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", post_comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>
<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "View comment", post_comment_path(post_id: @post, id: comment) %>
    </p>
  <% end %>
</div>

<br><%= link_to "New comment", new_post_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render partial: "form", locals: { comment: @comment, post: @post } %>

<br>

<div>
  <%= link_to "Back to comments", post_comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_post_comment_path(@comment) %> |
  <%= link_to "Back to comments", post_comments_path %>

  <%= button_to "Destroy this comment", post_comment_path(post_id: @post, id: @comment), method: :delete %>
</div>