config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  root "posts#index", as: "home"
  get "/notifications", to: "notifications#check"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'my_registrations'
  }

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :users, path: 'profile', except: [:create, :destroy, :edit, :new, :update] do
    member do
      post 'follow', to: 'follows#create'  # Create a follow relationship
      delete 'unfollow', to: 'follows#destroy'  # Remove a follow relationship
    end

    resources :posts, only: [:create, :new, :edit, :update, :destroy]

    get 'following/index'
    get 'followers/index'
  end

  resources :follows, only: [:update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :recipient, class_name: "User", foreign_key: "recipient_id"
  belongs_to :follow

  scope :pending_requests, -> { 
    joins(:follow).where(follows: { status: "pending" }) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def check
    @notifications = current_user.notifications
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/check.html.erb
<% if @notifications.pending_requests.empty? %>
  <h2>You don't have any notifications</h2>
<% end %>

<% @notifications.pending_requests.each do |notification| %>
  <p>
    <%= notification.message %> from
    <%= link_to "#{notification.sender.email}", user_path(notification.sender) %>
    
    <% follow = notification.follow %>

    <%= form_with model: follow, url: follow_path(follow), method: :patch do |f| %>
      <%= f.hidden_field :status, value: "Accepted" %>
      <%= f.submit "Accept" %>
    <% end %>
    <%= form_with model: follow, url: follow_path(follow), method: :patch do |f| %>
      <%= f.hidden_field :status, value: "Rejected" %>
      <%= f.submit "Reject" %>
    <% end %>
  </p>
<% end%>