config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  root "posts#index", as: "home"
  get "/notifications", to: "notifications#check"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'my_registrations'
  }

  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  resources :users, path: 'profile', except: [:create, :destroy, :edit, :new, :update] do
    member do
      post 'follow', to: 'follows#create'  # Create a follow relationship
      delete 'unfollow', to: 'follows#destroy'  # Remove a follow relationship
    end

    resources :posts, only: [:create, :new, :edit, :update, :destroy]

    get 'following/index'
    get 'followers/index'
  end

  resources :follows, only: [:update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes
  has_many :comments

  belongs_to :author, class_name: "User", foreign_key: "user_id"
  
  validates :body, presence: true
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <%= image_tag post.author.gravatar_url(:size => 30) %>
  <%= link_to "#{post.author.email }", user_path(post.author) %>
  <p>
    <%= post.body %>
  </p>
  <strong>Likes:</strong>
  <%= post.likes.count %> |
  <%= link_to "Comments", post_comments_path(post) %>:
  <%= post.comments.count %>

  <% if post.likes.exists?(user_id: current_user.id) %>
  <% like = post.likes.find_by(user_id: current_user.id) %>
  <%= button_to "Unlike post", post_like_path(post, like.id), method: :delete %>
<% else %>
  <%= button_to "Like post", post_likes_path(post), method: :post %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Home</h1>
<%= link_to "New post", new_post_path %>
<div id="posts">
  <% @posts.each do |post| %>
    <br><%= render post %>
    <p>
      <%= link_to "View Post", post %>
    </p>
  <% end %>
</div>
<%= form_tag destroy_user_session_path, method: :delete do %>
  <%= submit_tag "Sign out" %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<br><%= render @post %>
<% if current_user == @post.author %>
    <br><%= link_to "Edit post", edit_post_path(@post) %>
    <br><%= button_to "Delete post", @post, method: :delete %>
<% end %>